import Head from 'next/head'
import Slider from '../componentes/Slider'

export default function Home() {
  return (
    <>
      <Head>
        <title>Pagina Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="home" id="home">

        <Slider />

      </section>


      <section className="category">

        <h1 className="heading">adventure idea!</h1>

        <div className="box-container">

          <div className="box">
            <img src="images/category-1.jpg" alt="" />
            <h3>bungee jump</h3>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laborum, id.</p>
            <a href="#" className="btn">read more</a>
          </div>

          <div className="box">
            <img src="images/category-2.jpg" alt="" />
            <h3>zip lines</h3>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laborum, id.</p>
            <a href="#" className="btn">read more</a>
          </div>

          <div className="box">
            <img src="images/category-3.jpg" alt="" />
            <h3>Canoeing</h3>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laborum, id.</p>
            <a href="#" className="btn">read more</a>
          </div>

          <div className="box">
            <img src="images/category-4.jpg" alt="" />
            <h3>kayaking</h3>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Laborum, id.</p>
            <a href="#" className="btn">read more</a>
          </div>

        </div>

      </section>


      <section className="about" id="about">

        <div className="image">
          <img src="images/about-img.jpg" alt="" />
        </div>

        <div className="content">
          <h3>memorable outdoor experiences</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque voluptates corrupti natus necessitatibus beatae voluptatibus, deserunt quo soluta minima libero laborum, corporis error esse vitae placeat blanditiis reiciendis vel? Minima.</p>
          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident dicta doloremque placeat porro, ipsam quia at beatae atque odit iste?</p>
          <a href="#" className="btn">read more</a>
        </div>

      </section>


      <section className="shop" id="shop">

        <h1 className="heading">featured products</h1>

        <div className="swiper product-slider">

          <div className="swiper-wrapper">

            <div className="swiper-slide slide">
              <div className="image">
                <img src="images/product-1.jpg" alt="" />
                <div className="icons">
                  <a href="#" className="fas fa-shopping-cart"></a>
                  <a href="#" className="fas fa-eye"></a>
                  <a href="#" className="fas fa-share"></a>
                </div>
              </div>
              <div className="content">
                <h3>survival kits</h3>
                <div className="price"> $5.00 - $25.00 </div>
                <div className="stars">
                  <i className="fas fa-star"></i>
                  <i className="fas fa-star"></i>
                  <i className="fas fa-star"></i>
                  <i className="fas fa-star"></i>
                  <i className="fas fa-star-half-alt"></i>
                </div>
              </div>
            </div>

            <div className="swiper-slide slide">
              <div className="image">
                <img src="images/product-2.jpg" alt="" />
                <div className="icons">
                  <a href="#" className="fas fa-shopping-cart"></a>
                  <a href="#" className="fas fa-eye"></a>
                  <a href="#" className="fas fa-share"></a>
                </div>
              </div>
              <div className="content">
                <h3>survival kits</h3>
                <div className="price"> $5.00 - $25.00 </div>
                <div className="stars">
                  <i className="fas fa-star"></i>
                  <i className="fas fa-star"></i>
                  <i className="fas fa-star"></i>
                  <i className="fas fa-star"></i>
                  <i className="fas fa-star-half-alt"></i>
                </div>
              </div>
            </div>

            <div className="swiper-slide slide">
              <div className="image">
                <img src="images/product-3.jpg" alt="" />
                <div className="icons">
                  <a href="#" className="fas fa-shopping-cart"></a>
                  <a href="#" className="fas fa-eye"></a>
                  <a href="#" className="fas fa-share"></a>
                </div>
              </div>
              <div className="content">
                <h3>survival kits</h3>
                <div className="price"> $5.00 - $25.00 </div>
                <div className="stars">
                  <i className="fas fa-star"></i>
                  <i className="fas fa-star"></i>
                  <i className="fas fa-star"></i>
                  <i className="fas fa-star"></i>
                  <i className="fas fa-star-half-alt"></i>
                </div>
              </div>
            </div>

            <div className="swiper-slide slide">
              <div className="image">
                <img src="images/product-4.jpg" alt="" />
                <div className="icons">
                  <a href="#" className="fas fa-shopping-cart"></a>
                  <a href="#" className="fas fa-eye"></a>
                  <a href="#" className="fas fa-share"></a>
                </div>
              </div>
              <div className="content">
                <h3>survival kits</h3>
                <div className="price"> $5.00 - $25.00 </div>
                <div className="stars">
                  <i className="fas fa-star"></i>
                  <i className="fas fa-star"></i>
                  <i className="fas fa-star"></i>
                  <i className="fas fa-star"></i>
                  <i className="fas fa-star-half-alt"></i>
                </div>
              </div>
            </div>

            <div className="swiper-slide slide">
              <div className="image">
                <img src="images/product-5.jpg" alt="" />
                <div className="icons">
                  <a href="#" className="fas fa-shopping-cart"></a>
                  <a href="#" className="fas fa-eye"></a>
                  <a href="#" className="fas fa-share"></a>
                </div>
              </div>
              <div className="content">
                <h3>survival kits</h3>
                <div className="price"> $5.00 - $25.00 </div>
                <div className="stars">
                  <i className="fas fa-star"></i>
                  <i className="fas fa-star"></i>
                  <i className="fas fa-star"></i>
                  <i className="fas fa-star"></i>
                  <i className="fas fa-star-half-alt"></i>
                </div>
              </div>
            </div>

            <div className="swiper-slide slide">
              <div className="image">
                <img src="images/product-6.jpg" alt="" />
                <div className="icons">
                  <a href="#" className="fas fa-shopping-cart"></a>
                  <a href="#" className="fas fa-eye"></a>
                  <a href="#" className="fas fa-share"></a>
                </div>
              </div>
              <div className="content">
                <h3>survival kits</h3>
                <div className="price"> $5.00 - $25.00 </div>
                <div className="stars">
                  <i className="fas fa-star"></i>
                  <i className="fas fa-star"></i>
                  <i className="fas fa-star"></i>
                  <i className="fas fa-star"></i>
                  <i className="fas fa-star-half-alt"></i>
                </div>
              </div>
            </div>

          </div>

          <div className="swiper-button-next"></div>
          <div className="swiper-button-prev"></div>

        </div>

      </section>


      <section className="packages" id="packages">

        <h1 className="heading">popular packages</h1>

        <div className="box-container">

          <div className="box">
            <div className="image">
              <img src="images/img-1.jpg" alt="" />
            </div>
            <div className="content">
              <h3>featured tour package</h3>
              <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Numquam, eos.</p>
              <div className="price">$250 - $450</div>
              <a href="#" className="btn">explore now</a>
            </div>
          </div>

          <div className="box">
            <div className="image">
              <img src="images/img-2.jpg" alt="" />
            </div>
            <div className="content">
              <h3>featured tour package</h3>
              <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Numquam, eos.</p>
              <div className="price">$250 - $450</div>
              <a href="#" className="btn">explore now</a>
            </div>
          </div>

          <div className="box">
            <div className="image">
              <img src="images/img-3.jpg" alt="" />
            </div>
            <div className="content">
              <h3>featured tour package</h3>
              <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Numquam, eos.</p>
              <div className="price">$250 - $450</div>
              <a href="#" className="btn">explore now</a>
            </div>
          </div>

          <div className="box">
            <div className="image">
              <img src="images/img-4.jpg" alt="" />
            </div>
            <div className="content">
              <h3>featured tour package</h3>
              <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Numquam, eos.</p>
              <div className="price">$250 - $450</div>
              <a href="#" className="btn">explore now</a>
            </div>
          </div>

          <div className="box">
            <div className="image">
              <img src="images/img-5.jpg" alt="" />
            </div>
            <div className="content">
              <h3>featured tour package</h3>
              <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Numquam, eos.</p>
              <div className="price">$250 - $450</div>
              <a href="#" className="btn">explore now</a>
            </div>
          </div>

          <div className="box">
            <div className="image">
              <img src="images/img-6.jpg" alt="" />
            </div>
            <div className="content">
              <h3>featured tour package</h3>
              <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Numquam, eos.</p>
              <div className="price">$250 - $450</div>
              <a href="#" className="btn">explore now</a>
            </div>
          </div>

        </div>

      </section>



      <section className="reviews" id="reviews">

        <h1 className="heading">client's reviews</h1>

        <div className="swiper review-slider">

          <div className="swiper-wrapper">

            <div className="swiper-slide slide">
              <p className="text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia quidem laborum pariatur alias, culpa illum quaerat, aliquid laboriosam voluptatem nisi repellat obcaecati, adipisci esse ab delectus dolorum ut recusandae ipsam?</p>
              <div className="user">
                <img src="images/pic-1.png" alt="" />
                <div className="info">
                  <h3>john deo</h3>
                  <span>designer</span>
                </div>
              </div>
            </div>

            <div className="swiper-slide slide">
              <p className="text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia quidem laborum pariatur alias, culpa illum quaerat, aliquid laboriosam voluptatem nisi repellat obcaecati, adipisci esse ab delectus dolorum ut recusandae ipsam?</p>
              <div className="user">
                <img src="images/pic-2.png" alt="" />
                <div className="info">
                  <h3>john deo</h3>
                  <span>designer</span>
                </div>
              </div>
            </div>

            <div className="swiper-slide slide">
              <p className="text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia quidem laborum pariatur alias, culpa illum quaerat, aliquid laboriosam voluptatem nisi repellat obcaecati, adipisci esse ab delectus dolorum ut recusandae ipsam?</p>
              <div className="user">
                <img src="images/pic-3.png" alt="" />
                <div className="info">
                  <h3>john deo</h3>
                  <span>designer</span>
                </div>
              </div>
            </div>

            <div className="swiper-slide slide">
              <p className="text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia quidem laborum pariatur alias, culpa illum quaerat, aliquid laboriosam voluptatem nisi repellat obcaecati, adipisci esse ab delectus dolorum ut recusandae ipsam?</p>
              <div className="user">
                <img src="images/pic-4.png" alt="" />
                <div className="info">
                  <h3>john deo</h3>
                  <span>designer</span>
                </div>
              </div>
            </div>

            <div className="swiper-slide slide">
              <p className="text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia quidem laborum pariatur alias, culpa illum quaerat, aliquid laboriosam voluptatem nisi repellat obcaecati, adipisci esse ab delectus dolorum ut recusandae ipsam?</p>
              <div className="user">
                <img src="images/pic-5.png" alt="" />
                <div className="info">
                  <h3>john deo</h3>
                  <span>designer</span>
                </div>
              </div>
            </div>

            <div className="swiper-slide slide">
              <p className="text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quia quidem laborum pariatur alias, culpa illum quaerat, aliquid laboriosam voluptatem nisi repellat obcaecati, adipisci esse ab delectus dolorum ut recusandae ipsam?</p>
              <div className="user">
                <img src="images/pic-6.png" alt="" />
                <div className="info">
                  <h3>john deo</h3>
                  <span>designer</span>
                </div>
              </div>
            </div>

          </div>

        </div>

      </section>


      <section className="services">

        <h1 className="heading"> what we offer </h1>

        <div className="box-container">

          <div className="box">
            <img src="images/serv-1.png" alt="" />
            <h3>complete guide</h3>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellendus, nihil?</p>
            <a href="#" className="btn">read more</a>
          </div>

          <div className="box">
            <img src="images/serv-2.png" alt="" />
            <h3>custom packages</h3>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellendus, nihil?</p>
            <a href="#" className="btn">read more</a>
          </div>

          <div className="box">
            <img src="images/serv-3.png" alt="" />
            <h3>family trips</h3>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellendus, nihil?</p>
            <a href="#" className="btn">read more</a>
          </div>

          <div className="box">
            <img src="images/serv-4.png" alt="" />
            <h3>train guides</h3>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellendus, nihil?</p>
            <a href="#" className="btn">read more</a>
          </div>

          <div className="box">
            <img src="images/serv-5.png" alt="" />
            <h3>adventure trail</h3>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellendus, nihil?</p>
            <a href="#" className="btn">read more</a>
          </div>

          <div className="box">
            <img src="images/serv-6.png" alt="" />
            <h3>various adventures</h3>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repellendus, nihil?</p>
            <a href="#" className="btn">read more</a>
          </div>

        </div>

      </section>


      <section className="blogs" id="blogs">

        <h1 className="heading"> our daily posts </h1>

        <div className="swiper blogs-slider">

          <div className="swiper-wrapper">

            <div className="swiper-slide slide">
              <img src="images/img-1.jpg" alt="" />
              <div className="icons">
                <a href="#"> <i className="fas fa-calendar"></i> 21st may, 2021 </a>
                <a href="#"> <i className="fas fa-user"></i> by admin </a>
              </div>
              <h3>blog title goes here.</h3>
              <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reprehenderit, deserunt.</p>
              <a href="#" className="btn">read more</a>
            </div>

            <div className="swiper-slide slide">
              <img src="images/img-2.jpg" alt="" />
              <div className="icons">
                <a href="#"> <i className="fas fa-calendar"></i> 21st may, 2021 </a>
                <a href="#"> <i className="fas fa-user"></i> by admin </a>
              </div>
              <h3>blog title goes here.</h3>
              <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reprehenderit, deserunt.</p>
              <a href="#" className="btn">read more</a>
            </div>

            <div className="swiper-slide slide">
              <img src="images/img-3.jpg" alt="" />
              <div className="icons">
                <a href="#"> <i className="fas fa-calendar"></i> 21st may, 2021 </a>
                <a href="#"> <i className="fas fa-user"></i> by admin </a>
              </div>
              <h3>blog title goes here.</h3>
              <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reprehenderit, deserunt.</p>
              <a href="#" className="btn">read more</a>
            </div>

            <div className="swiper-slide slide">
              <img src="images/img-4.jpg" alt="" />
              <div className="icons">
                <a href="#"> <i className="fas fa-calendar"></i> 21st may, 2021 </a>
                <a href="#"> <i className="fas fa-user"></i> by admin </a>
              </div>
              <h3>blog title goes here.</h3>
              <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reprehenderit, deserunt.</p>
              <a href="#" className="btn">read more</a>
            </div>

            <div className="swiper-slide slide">
              <img src="images/img-5.jpg" alt="" />
              <div className="icons">
                <a href="#"> <i className="fas fa-calendar"></i> 21st may, 2021 </a>
                <a href="#"> <i className="fas fa-user"></i> by admin </a>
              </div>
              <h3>blog title goes here.</h3>
              <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reprehenderit, deserunt.</p>
              <a href="#" className="btn">read more</a>
            </div>

            <div className="swiper-slide slide">
              <img src="images/img-6.jpg" alt="" />
              <div className="icons">
                <a href="#"> <i className="fas fa-calendar"></i> 21st may, 2021 </a>
                <a href="#"> <i className="fas fa-user"></i> by admin </a>
              </div>
              <h3>blog title goes here.</h3>
              <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reprehenderit, deserunt.</p>
              <a href="#" className="btn">read more</a>
            </div>

          </div>

        </div>

      </section>

      <section className="newsletter">

        <div className="content">
          <h1 className="heading">subscirbe now</h1>
          <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Laboriosam ipsam repellat nostrum esse officiis unde quisquam corporis doloremque adipisci similique!</p>
          <form action="">
            <input type="email" name="" placeholder="enter your email" id="" className="email" />
            <input type="submit" value="subscirbe" className="btn" />
          </form>
        </div>
      </section>



      <section className="clients">

        <div className="swiper clients-slider">
          <div className="swiper-wrapper">
            <div className="swiper-slide silde"><img src="images/client-logo-1.png" alt="" /></div>
            <div className="swiper-slide silde"><img src="images/client-logo-2.png" alt="" /></div>
            <div className="swiper-slide silde"><img src="images/client-logo-3.png" alt="" /></div>
            <div className="swiper-slide silde"><img src="images/client-logo-4.png" alt="" /></div>
          </div>
        </div>

      </section>



    </>
  )
}
